name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - run: flutter build apk && flutter build appbundle

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
#   release:
#     name: Release app to internal track
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Get appbundle from artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: appbundle
#       - name: Release app to internal track
#         uses: r0adkll/upload-google-play@v1
#         with:
#           serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
#           packageName: com.app.package_name
#           releaseFiles: app-release.aab
#           track: alpha
#           status: completed
