name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Create Android Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # android_keystore 파일 생성
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Creating key.properties file
        env:
          PROPERTIES_PATH: "./android/key.properties"
          # echo > 파일명 : 주어진 파일명으로 파일을 생성하거나 이미 존재하는 파일을 덮어쓰면서 텍스트를 작성합니다 (= redirection)
          # echo >> 파일명 : 주어진 파일명의 파일에 텍스트를 추가합니다. 파일이 존재하지 않으면 새로운 파일을 생성합니다. (= append)
        run: |
          echo keyPassword=\${{ secrets.KEY_PROPERTY_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PROPERTY_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_PROPERTY_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ steps.android_keystore.outputs.filePath }} >> ${{env.PROPERTIES_PATH}}

      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.7.12"
          channel: "stable"

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - run: flutter build apk && flutter build appbundle

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
#   release:
#     name: Release app to internal track
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Get appbundle from artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: appbundle
#       - name: Release app to internal track
#         uses: r0adkll/upload-google-play@v1
#         with:
#           serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
#           packageName: com.app.package_name
#           releaseFiles: app-release.aab
#           track: alpha
#           status: completed
